ALTER TABLE "SITE_Leads" ADD COLUMN IF NOT EXISTS "conversion_value" NUMERIC DEFAULT 0;
ALTER TABLE "SITE_Leads" ADD COLUMN IF NOT EXISTS "conversion_summary" TEXT;
ALTER TABLE "SITE_Leads" ADD COLUMN IF NOT EXISTS "conversion_type" TEXT;
