-- Enable pgcrypto for password hashing
create extension if not exists pgcrypto;

-- 1. Helper: Create User RPC (For Admin Panel)
create or replace function admin_create_user(
    new_email text,
    new_password text,
    new_name text,
    new_role_id uuid default null,
    new_status text default 'Active',
    new_receives_leads boolean default false
)
returns uuid
language plpgsql
security definer -- Run as creator (postgres) to allow auth modifications
as $$
declare
  new_id uuid;
begin
  -- 1. Insert into Auth Users
  insert into auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at,
    confirmation_token,
    recovery_token
  ) values (
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    new_email,
    crypt(new_password, gen_salt('bf')),
    now(),
    '{"provider": "email", "providers": ["email"]}',
    json_build_object('name', new_name),
    now(),
    now(),
    '',
    ''
  ) returning id into new_id;

  -- 2. Insert into Public SITE_Users (Application Data)
  -- Note: We use the SAME ID generated by auth
  insert into public."SITE_Users" (
    id,
    name,
    email,
    role_id,
    status,
    receives_leads,
    password -- Store visible for admin reference if desired, or skip
  ) values (
    new_id,
    new_name,
    new_email,
    new_role_id,
    new_status,
    new_receives_leads,
    new_password -- Storing plain text password as per your existing schema (optional but requested impliclty)
  );

  return new_id;
end;
$$;

-- 2. Helper: Update User RPC
create or replace function admin_update_user(
    target_user_id uuid,
    new_email text,
    new_password text,
    new_name text,
    new_role_id uuid,
    new_status text
)
returns void
language plpgsql
security definer
as $$
begin
  -- Update Auth (Email/Password)
  update auth.users
  set 
    email = new_email,
    encrypted_password = case when new_password is not null and new_password <> '' then crypt(new_password, gen_salt('bf')) else encrypted_password end,
    updated_at = now(),
    raw_user_meta_data = jsonb_set(raw_user_meta_data, '{name}', to_jsonb(new_name))
  where id = target_user_id;

  -- Update Public
  update public."SITE_Users"
  set
    name = new_name,
    email = new_email,
    role_id = new_role_id,
    status = new_status,
    password = case when new_password is not null and new_password <> '' then new_password else password end
  where id = target_user_id;
end;
$$;

-- 3. Helper: Delete User RPC
create or replace function admin_delete_user(target_user_id uuid)
returns void
language plpgsql
security definer
as $$
begin
  delete from public."SITE_Users" where id = target_user_id;
  delete from auth.users where id = target_user_id;
end;
$$;

-- 4. FIX: Sync Missing Users from SITE_Users to Auth
-- This block attempts to create Auth users for any SITE_User that has a password but no Auth record.
do $$
declare
    rec record;
    exist_id uuid;
begin
    for rec in select * from public."SITE_Users" where password is not null and password <> '' loop
        -- Check if exists in auth
        select id into exist_id from auth.users where email = rec.email;
        
        if exist_id is null then
            -- Create missing auth user using the stored public ID to maintain link
            insert into auth.users (
                instance_id,
                id,
                aud,
                role,
                email,
                encrypted_password,
                email_confirmed_at,
                raw_app_meta_data,
                raw_user_meta_data,
                created_at,
                updated_at
            ) values (
                '00000000-0000-0000-0000-000000000000',
                rec.id, -- FORCE SAME ID
                'authenticated',
                'authenticated',
                rec.email,
                crypt(rec.password, gen_salt('bf')),
                now(),
                '{"provider": "email", "providers": ["email"]}',
                json_build_object('name', rec.name),
                now(),
                now()
            );
        end if;
    end loop;
end;
$$;
