
-- ATUALIZAÇÃO TABELA DE CURSOS (SITE_Courses)
ALTER TABLE "SITE_Courses" ADD COLUMN IF NOT EXISTS "hotels_info" TEXT;
ALTER TABLE "SITE_Courses" ADD COLUMN IF NOT EXISTS "type" TEXT DEFAULT 'Course';
ALTER TABLE "SITE_Courses" ADD COLUMN IF NOT EXISTS "recycling_price" NUMERIC;
ALTER TABLE "SITE_Courses" ADD COLUMN IF NOT EXISTS "start_time" TEXT;
ALTER TABLE "SITE_Courses" ADD COLUMN IF NOT EXISTS "end_time" TEXT;
ALTER TABLE "SITE_Courses" ADD COLUMN IF NOT EXISTS "date_end" DATE;
ALTER TABLE "SITE_Courses" ADD COLUMN IF NOT EXISTS "map_url" TEXT;
ALTER TABLE "SITE_Courses" ADD COLUMN IF NOT EXISTS "schedule" TEXT;
ALTER TABLE "SITE_Courses" ADD COLUMN IF NOT EXISTS "location_type" TEXT;

-- Campos de Endereço no Curso
ALTER TABLE "SITE_Courses" ADD COLUMN IF NOT EXISTS "zip_code" TEXT;
ALTER TABLE "SITE_Courses" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "SITE_Courses" ADD COLUMN IF NOT EXISTS "address_number" TEXT;
ALTER TABLE "SITE_Courses" ADD COLUMN IF NOT EXISTS "address_neighborhood" TEXT;
ALTER TABLE "SITE_Courses" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "SITE_Courses" ADD COLUMN IF NOT EXISTS "state" TEXT;
ALTER TABLE "SITE_Courses" ADD COLUMN IF NOT EXISTS "latitude" NUMERIC;
ALTER TABLE "SITE_Courses" ADD COLUMN IF NOT EXISTS "longitude" NUMERIC;

-- ATUALIZAÇÃO TABELA DE INSCRIÇÕES (SITE_Enrollments)
ALTER TABLE "SITE_Enrollments" ADD COLUMN IF NOT EXISTS "is_credentialed" BOOLEAN DEFAULT FALSE;
ALTER TABLE "SITE_Enrollments" ADD COLUMN IF NOT EXISTS "total_amount" NUMERIC;
ALTER TABLE "SITE_Enrollments" ADD COLUMN IF NOT EXISTS "zip_code" TEXT;
ALTER TABLE "SITE_Enrollments" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "SITE_Enrollments" ADD COLUMN IF NOT EXISTS "address_number" TEXT;
ALTER TABLE "SITE_Enrollments" ADD COLUMN IF NOT EXISTS "address_neighborhood" TEXT;
ALTER TABLE "SITE_Enrollments" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "SITE_Enrollments" ADD COLUMN IF NOT EXISTS "state" TEXT;
