import { lpTranslations, type LPLanguage, type LPTranslation } from './lpErgonomiaTranslations';

// Vocabulário específico desta landing; as outras páginas mantêm as suas versões.
const portugalCopy: Record<string, string> = {
    "APRESENTAÇÃO EXCLUSIVA PARA PILOTOS & MECÂNICOS": "FORMAÇÃO ONLINE · PILOTOS E MECÂNICOS",
    "Ativar Som": "Ativar som",
    "Áudio Ligado": "Som ligado",
    "SEU ÁUDIO ESTÁ DESLIGADO — CLIQUE PARA OUVIR": "ATIVA O SOM PARA OUVIR A APRESENTAÇÃO",
    "Seu navegador não suporta vídeos.": "O teu navegador não suporta vídeos.",
    "CONHEÇA O MÉTODO W-TECH": "CONHECE O MÉTODO W-TECH",
    "Assistir à apresentação do curso": "Ver a apresentação da formação",
    "Quero dominar os ajustes da minha moto": "Quero aprender a afinar a minha mota",
    "Certificado incluso": "Certificado incluído",
    "Explore o curso no seu ritmo": "Explora a formação ao teu ritmo",
    "Diferencial Competitivo": "Especialização técnica",
    "Dono de Oficina": "Responsável de oficina",
    "Seus clientes pedem ajustes de cliques que a equipe não sabe resolver,": "Os teus clientes procuram afinações que a equipa ainda não domina,",
    "perdendo serviço e fidelidade": "e acabam por recorrer",
    "para oficinas especializadas de Off-Road. Dê esse diferencial à sua equipe.": "a oficinas especializadas em Off-Road. Desenvolve esta competência na tua equipa.",
    "Quero Garantir Minha Vaga": "Quero conhecer a formação",
    "Entenda o conceito": "Compreende o método",
    "Qual o Segredo do": "O que muda com uma",
    "Acerto Perfeito": "Suspensão Afinada",
    "Não importa o quanto o motor da sua moto é forte se a suspensão não consegue colocar a potência no chão.": "A potência do motor só se traduz em tração quando a suspensão acompanha o terreno.",
    "Quando molas, óleo, cliques (retorno/compressão), SAG e pneus estão finamente ajustados para o": "Quando molas, óleo, cliques de retorno e compressão, SAG e pneus estão afinados para o",
    "seu nível e modalidade Off-Road": "teu nível e a tua modalidade",
    ", tudo muda: a moto não espalha, a tração é constante nas subidas e os impactos param de moer os seus braços e sua lombar.": ", a mota torna-se mais previsível: ganhas tração nas subidas, controlo nas curvas e conforto perante os impactos.",
    "O acerto da suspensão muda a moto da água para o vinho. É investimento em performance e segurança.": "Uma boa afinação melhora o comportamento da mota e a tua confiança aos comandos.",
    "Conteúdo Completo": "Programa da formação",
    "Bônus Exclusivo": "Bónus prático",
    "Tudo o que você precisa saber sobre suspensão Off-Road, do SAG ao clique, em aulas gravadas em estúdio com qualidade W-Tech.": "Aprende os fundamentos da suspensão Off-Road, do SAG aos cliques, com aulas gravadas que podes rever ao teu ritmo.",
    "Módulo Bônus Exclusivo": "Módulo bónus com demonstração prática",
    "O Piloto Que Testou Tudo Na Prática — Para Você Ver A Diferença": "Da teoria à mota: vê a diferença de cada afinação",
    "Não basta entender a teoria. Rafa Paschoalin — piloto de alta performance — pegou a moto,": "Rafa Paschoalin leva a teoria para o terreno:",
    "desregulou e regulou cada componente ao vivo": "altera e volta a afinar cada componente na mota",
    ", para que você veja, na prática, o que muda com cada ajuste. Este é o tipo de conteúdo que você não encontra em nenhum outro lugar.": ", para que possas observar o efeito de cada ajuste e compreender como aplicar o método.",
    "Rafa pega a moto regulada,": "Rafa parte de uma mota afinada,",
    "desregula ela ao vivo": "altera os ajustes durante a demonstração",
    "— e você sente a diferença. Isso é o que transforma conhecimento em resultado real.": "— e mostra-te a diferença. Assim, cada conceito ganha uma aplicação prática.",
    "Seus": "Os teus",
    "3.000 mecânicos e pilotos capacitados": "3.000 mecânicos e pilotos formados",
    "Referência nacional no acerto, preparação e revalvulação de": "Referência no Brasil na afinação, preparação e revalvulação de",
    "👉 Domínio técnico em suspensão: da simples manutenção à personalização profunda com shims, fluídos e kits de revalvulação.": "Domínio técnico da suspensão: da manutenção à personalização com lâminas, fluidos e kits de revalvulação.",
    "da teoria para as trilhas de performance e exigência máxima.": "da teoria para os trilhos e as condições de maior exigência.",
    "Quero Aprender com os Melhores": "Quero aprender com a W-Tech",
    "Da aula para": "Da aula para",
    "a sua moto": "a tua mota",
    "Ao garantir sua vaga agora, você leva ferramentas complementares que nossa própria equipe usa.": "Leva para a prática as folhas de cálculo e os materiais de consulta utilizados pela nossa equipa.",
    "Incluso no curso": "Incluído na formação",
    "Planilha de Regulagem de SAG": "Folha de cálculo para afinação do SAG",
    "Planilha de Regulagem de PSI": "Folha de cálculo para pressão dos pneus",
    "Comparativo de Óleos": "Comparação de óleos",
    "Comparativo de Molas": "Comparação de molas",
    "Um ano para assistir, revisar e aplicar cada ajuste. Aulas em vídeo, materiais de apoio e certificado em uma única formação.": "Tens 12 meses para ver, rever e aplicar cada afinação. Aulas em vídeo, materiais de apoio e certificado numa única formação.",
    "Suporte Técnico na Plataforma": "Apoio técnico na plataforma",
    "BÔNUS: Planilha de Regulagem de SAG": "BÓNUS: folha de cálculo para o SAG",
    "BÔNUS: Planilha de Regulagem de PSI": "BÓNUS: folha de cálculo para pressão dos pneus",
    "Quero Regular Minha Suspensão Agora": "Quero começar a formação",
    "Tenho uma dúvida. Falar com a equipe": "Tenho uma dúvida. Falar com a equipa",
    "Vagas sujeitas à disponibilidade": "Aulas gravadas · ao teu ritmo",
    "Mas sua maior conquista não foi apenas o conhecimento técnico, foi a criação da": "Além da experiência técnica, Alex fundou a",
    "Hoje, como instrutor e especialista, Alex usa o método que desenvolveu trabalhando nos bastidores das corridas para forjar mecânicos autônomos e pilotos que buscam a mais pura precisão.": "Como formador e especialista, Alex partilha o método que desenvolveu nas competições com mecânicos e pilotos que procuram autonomia e precisão na afinação.",
    "Conheça a história": "Conhecer a formação",
    "O próximo ajuste começa com você.": "A próxima afinação começa contigo.",
    "Ergonomia com Paschoalin (na moto real)": "Ergonomia com Paschoalin na mota",
    "Ajuste do guidão na prática": "Afinação do guiador na prática",
    "Ajuste das manetes no campo": "Afinação das manetes no terreno",
    "Ajuste preciso do freio": "Afinação do travão",
    "Ajuste e posicionamento do câmbio": "Afinação e posição do seletor de mudanças",
    "Check Down: verificação completa": "Verificação completa da mota",
    "Desregulando a moto (para sentir a diferença)": "Alterar as afinações para perceber a diferença",
    "Moto regulada — Teste e comparação final": "Mota afinada — teste e comparação final",
    "Menos dor e fadiga na pilotagem": "Menos fadiga na condução",
    "Mais controle e precisão nas manobras": "Mais controlo e precisão nas manobras",
    "Maior segurança para você e sua moto": "Maior segurança para ti e para a tua mota",
    "Instrutor de +3.000 Alunos": "Formador de mais de 3.000 alunos",
    "Referência Nacional em Customização": "Referência no Brasil em personalização",
    "Curso de Suspensão Off-Road | Regule a Suspensão da Sua Moto — W-Tech": "Curso de Suspensões Online | Aprende a Afinar a Tua Mota — W-Tech",
    "Curso online de regulagem de suspensão Off-Road: SAG, molas, cliques, óleo e ergonomia. Do zero ao acerto, com prática real na moto. Acesso por 12 meses + bônus.": "Formação online de suspensões Off-Road: SAG, molas, cliques e ergonomia. Aprende a afinar a tua mota ao teu ritmo, com 12 meses de acesso e materiais incluídos.",
    "Aprenda a regular a suspensão da sua moto do zero: SAG, molas, cliques e ergonomia, com prática real. 11 módulos + bônus Paschoalin.": "Aprende a afinar a suspensão da tua mota: SAG, molas, cliques e ergonomia. Aulas online e demonstrações práticas com Alex Crepaldi e Rafa Paschoalin.",
    "Curso de Suspensão Off-Road — W-Tech Brasil": "Formação Online de Suspensões Off-Road — W-Tech",
    "Alex Crepaldi ajustando a suspensão de uma moto Off-Road": "Alex Crepaldi a afinar a suspensão de uma mota Off-Road"
};

export const localizePilotCopy = (language: LPLanguage, text: string): string =>
    language === 'pt-PT' ? (portugalCopy[text] ?? text) : text;

export const getPilotLandingTranslation = (language: LPLanguage): LPTranslation => {
    const base = lpTranslations[language];
    if (language === 'pt-BR') return {
        ...base,
        hero: {
            ...base.hero,
            titlePart1: 'O único curso que você precisa para',
            titleHighlight: 'acertar a suspensão da sua moto.',
            subtitle: 'Aprenda acerto, regulagem, SAG e ergonomia para ajustar a moto ao piloto e ao terreno. Autonomia para pilotar com mais controle — e conhecimento para entregar um acerto personalizado na oficina.',
        },
        profiles: {
            ...base.profiles,
            label: 'Um método. Duas formas de transformar a pilotagem.',
            titlePart1: 'Autonomia para o piloto.',
            titleHighlight: 'Diferencial para a oficina.',
            desc: 'O melhor ajuste começa por quem pilota: peso, posição na moto, nível de experiência e terreno. Aprenda a combinar esses fatores em um acerto feito para cada pessoa.',
            items: [
                { tag: 'A sua moto, do seu jeito', title: 'Piloto', pain: 'Entenda o que ajustar, por que ajustar e como avaliar a diferença. Regule o SAG, os cliques e a ergonomia para o seu peso e sua forma de pilotar, com autonomia para evoluir o acerto da sua moto.' },
                { tag: 'O terreno muda. O acerto acompanha.', title: 'Trilha / Off-Road', pain: 'Areia, pedras, lama, trilha ou pista: aprenda a interpretar o comportamento da moto e adaptar a regulagem às condições de cada terreno, dentro dos recursos da sua suspensão.' },
                { tag: 'Acerto personalizado', title: 'Mecânico / Preparador', pain: 'Cada piloto tem um peso, uma postura e uma necessidade. Aprenda a combinar suspensão, SAG e ergonomia para entregar a moto regulada para aquele cliente — e explicar o que foi ajustado e por quê.' },
                { tag: 'Uma entrega que faz diferença', title: 'Dono de Oficina', pain: 'Transforme o acerto personalizado em parte da entrega da sua oficina. Avalie o perfil do cliente, o terreno em que ele pilota e o uso da moto para oferecer uma regulagem orientada à pessoa que vai pilotar.' },
            ],
        },
        offer: { ...base.offer, title: 'O curso completo de acerto da sua moto + bônus' },
    };
    if (language !== 'pt-PT') return base;
    return {
        ...base,
        hero: {
            ...base.hero,
            titlePart1: 'O único curso de que precisas para',
            titleHighlight: 'acertar a suspensão da tua mota.',
            subtitle: 'Aprende afinação de suspensões, SAG e ergonomia para adaptar a mota ao piloto e ao terreno. Autonomia para conduzir com mais controlo — e conhecimento para entregar uma afinação personalizada na oficina.',
        },
        profiles: {
            ...base.profiles,
            label: 'Um método. Duas formas de transformar a condução.',
            titlePart1: 'Autonomia para o piloto.',
            titleHighlight: 'Especialização para a oficina.',
            desc: 'A afinação começa por quem conduz: peso, posição na mota, experiência e terreno. Aprende a combinar estes fatores numa afinação feita para cada pessoa.',
            items: [
                { tag: 'A tua mota, à tua medida', title: 'Piloto', pain: 'Compreende o que afinar, porquê e como avaliar a diferença. Ajusta o SAG, os cliques e a ergonomia ao teu peso e à tua forma de conduzir, com autonomia para evoluir a afinação da tua mota.' },
                { tag: 'O terreno muda. A afinação acompanha.', title: 'Trilhos / Off-Road', pain: 'Areia, pedras, lama, trilhos ou pista: aprende a interpretar o comportamento da mota e a adaptar a afinação às condições de cada terreno, dentro das possibilidades da tua suspensão.' },
                { tag: 'Afinação personalizada', title: 'Mecânico / Preparador', pain: 'Cada piloto tem um peso, uma postura e necessidades próprias. Aprende a combinar suspensão, SAG e ergonomia para entregar a mota afinada à medida daquele cliente — e explicar cada ajuste.' },
                { tag: 'Uma entrega que faz a diferença', title: 'Responsável de oficina', pain: 'Integra a afinação personalizada na entrega da tua oficina. Avalia o perfil do cliente, o terreno onde conduz e a utilização da mota para oferecer uma afinação orientada à pessoa que a vai conduzir.' },
            ],
        },
        modules: { ...base.modules, cta: 'Conhecer as condições de inscrição' },
        offer: { ...base.offer, badge: 'Formação online', title: 'A formação completa de afinação da tua mota + bónus' },
        faq: {
            ...base.faq,
            items: [
                { q: 'Posso fazer a formação a partir de Portugal?', a: 'Sim. A formação é 100% online, com aulas gravadas. Podes acompanhar no computador, tablet ou telemóvel, sem deslocações nem horários fixos.' },
                { q: 'Em que português são dadas as aulas?', a: 'As aulas são apresentadas pelos formadores brasileiros da W-Tech, em português do Brasil. A formação aborda princípios de afinação aplicáveis à tua mota.' },
                { q: 'Preciso de experiência em mecânica?', a: 'Não. Começas pelos fundamentos e avanças para o SAG, as molas, a hidráulica e os cliques, com demonstrações práticas.' },
                { q: 'Como pago a formação?', a: 'Para inscrições internacionais, o pagamento é processado pela Hotmart. Consulta os meios de pagamento disponíveis e o valor final antes de confirmar a compra.' },
                { q: 'Durante quanto tempo tenho acesso?', a: 'Tens acesso durante 12 meses após a confirmação do pagamento. Podes ver e rever as aulas ao teu ritmo durante esse período.' },
                { q: 'Recebo um certificado?', a: 'Sim. Ao concluir a formação, recebes o certificado digital de conclusão emitido pela W-Tech.' },
                { q: 'A formação serve para a minha mota?', a: 'Os princípios de SAG, molas, hidráulica e ergonomia são aplicáveis a diferentes motas Off-Road. Os ajustes concretos devem respeitar as especificações da tua mota.' },
                { q: 'Onde posso esclarecer uma dúvida antes de me inscrever?', a: 'Na secção de inscrição encontras o contacto da nossa equipa por WhatsApp.' },
            ],
        },
    };
};
